services:
  - type: web
    name: results-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: results-db
          property: connectionString

databases:
  - name: results-db
    plan: free

